---
- name: Installing elk
  hosts: elk
  become: true
  tasks:
  - name: PoggersMap
    ansible.posix.sysctl:
      name: vm.max_map_count
      value: 262144
      state: present
  - name: install docker.io
    apt:
#      update_cache: yes
      name: docker.io
      state: present
  - name: Install pip3
    apt:
      name: python3-pip
      state: present
  - name: Install Docker python module
    pip:
      name: docker
      state: present
  - name: PoggerElk
    docker_container:
      name: elk
      image: sebp/elk:761
      state: started
      published_ports:
        - 5601:5601
        - 9200:9200
        - 5044:5044